--[[  Scenario                                                           		]]--
--[[  																					]]--
--[[	Generated by FAF Map Editor								]]--
--[[	Contact: ozonexo3@gmail.com								]]--
--[[																					]]--
Scenario = {
    next_area_id = '4',
    --[[																				]]--
    --[[  Props                                                                    ]]--
    --[[																				]]--
    Props = {
    },
    --[[																				]]--
    --[[  Areas                                                                    ]]--
    --[[																				]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 0, 0, 0, 0),
        },
    },
    --[[																				]]--
    --[[  Markers																]]--
    --[[																				]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {

            },
        },
    },
    Chains = {

    },
    --[[																				]]--
    --[[  Orders																	]]--
    --[[																				]]--
    next_queue_id = '1',
    Orders = {
    },
    --[[																				]]--
    --[[  Platoons																]]--
    --[[																				]]--
    next_platoon_id = '1',
    Platoons = 
    {
    },
    --[[																				]]--
    --[[  Armies																	]]--
    --[[																				]]--
    next_army_id = '5',
    next_group_id = '1',
    next_unit_id = '2',
    Armies = 
    {
        ['ARMY_2'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
			
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {

                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
        ['ARMY_1'] =  
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
			
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {

                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '0',
                Builders = {
                },
            },
        },
    },
}